### ISSUE TITLE
White space viewUsers

### ISSUE THREAD

**Issue by ghost** [SJPCompany/Bigrivers#30]
There is a white space under the table and the menu while the footer is placed to the right side instead of under the table.

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Tables in de backend stylen als die in AdminLTE](https://trello.com/c/2hXTKtP1/89-1-tables-in-de-backend-stylen-als-die-in-adminlte)

**Comment by Romy96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Tables in de backend stylen als die in AdminLTE](https://trello.com/c/2hXTKtP1/89-1-tables-in-de-backend-stylen-als-die-in-adminlte)

**Comment by ghost** [comment]
Some divs have to be closed. After that it was solved.
