### ISSUE TITLE
User update

### ISSUE THREAD

**Issue by Elise39u** [SJPCompany/Bigrivers#31]
Waneer er een beheerder of programmeur een use updated wordt het password gehaste password dat al gehast was nog een keer gehast

**Comment by pieter19998** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Update fixen](https://trello.com/c/YbiFo5zK/134-user-update-fixen)

**Comment by Elise39u** [comment]
We hebben het gefixt door er een validatie op te gooien en het password veld leeg te laten voor de gebruiker
